//! The committed codegen must match what api_gen produces from the current `api/*.def`.
//!
//! Replaces the CI step that ran the generator and asserted `git diff --exit-code`: this
//! regenerates into a temp dir and compares, so the check never mutates the working tree
//! and reports which file drifted rather than dumping a diff.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// Stamped into every file api_gen writes, and absent from hand-maintained neighbours.
const GENERATED_MARKER: &[u8] = b"@generated by api_gen";

/// Every generated file under `dir`, keyed by its path relative to `dir`.
fn collect(dir: &Path) -> BTreeMap<PathBuf, Vec<u8>> {
    let mut found = BTreeMap::new();
    let mut stack = vec![dir.to_path_buf()];
    while let Some(current) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&current) else {
            continue; // A never-written output dir is simply empty on both sides.
        };
        for entry in entries.filter_map(Result::ok) {
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
            } else {
                let rel = path
                    .strip_prefix(dir)
                    .expect("walked under dir")
                    .to_path_buf();
                found.insert(rel, std::fs::read(&path).expect("read generated file"));
            }
        }
    }
    found
}

#[test]
fn committed_codegen_matches_the_idl() {
    let repo = flowi_vfs_codegen::repo_root();
    let temp = std::env::temp_dir().join(format!("flowi_vfs_codegen_check_{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&temp);

    let targets = flowi_vfs_codegen::targets(&repo, &temp);
    for target in &targets {
        api_gen::generate(&target.config)
            .unwrap_or_else(|e| panic!("regenerating the {} target: {e}", target.name));
    }

    let mut drifted = Vec::new();
    let mut checked = 0usize;
    for dir in targets.iter().flat_map(|t| t.outputs) {
        let fresh = collect(&temp.join(dir));
        let committed = collect(&repo.join(dir));

        for (rel, bytes) in &fresh {
            checked += 1;
            match committed.get(rel) {
                Some(on_disk) if on_disk == bytes => {}
                Some(_) => drifted.push(format!("{}/{} differs", dir, rel.display())),
                None => drifted.push(format!("{}/{} is missing", dir, rel.display())),
            }
        }
        // An output dir may also hold hand-maintained files - flowi/exports/ carries
        // flowi_handwritten.txt beside the generated flowi.def. Only a file api_gen
        // stamped is one it still owns, so only those can go stale.
        for (rel, bytes) in committed
            .iter()
            .filter(|(rel, _)| !fresh.contains_key(*rel))
        {
            if bytes
                .windows(GENERATED_MARKER.len())
                .any(|w| w == GENERATED_MARKER)
            {
                drifted.push(format!(
                    "{}/{} is stale (no def produces it)",
                    dir,
                    rel.display()
                ));
            }
        }
    }
    let _ = std::fs::remove_dir_all(&temp);

    assert!(
        checked > 0,
        "generated nothing - the config's output dirs are wrong"
    );
    assert!(
        drifted.is_empty(),
        "committed codegen is out of date; run `cargo regen`:\n  {}",
        drifted.join("\n  ")
    );
}
