// @generated by api_gen - DO NOT EDIT. Regenerate with cargo regen.

#pragma once

#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct FlVfsEntry FlVfsEntry;

// Directory-listing callback - invoked once per entry during a directory
// listing. user_data is the caller's opaque pointer passed to the listing
// call; entry is valid only for the duration of the callback. Returns true to
// continue listing, false to stop.
typedef bool (*FlVfsListingCallback)(void* user_data, const FlVfsEntry* entry);


#ifdef __cplusplus
}
#endif
