// @generated by api_gen - DO NOT EDIT. Regenerate with cargo regen.

#pragma once

#include <stdbool.h>
#include <stdint.h>
#include <flowi/core/string.h>
#include <flowi/vfs/vfs_listing.h>

#ifdef __cplusplus
extern "C" {
#endif

// VFS operation status - hierarchical error codes drivers return. Drivers set
// the most specific code possible. Codes are grouped in hundreds (file/IO/
// permission/resource/archive/network/HTTP/generic).
typedef enum FlVfsStatus {
    // Success.
    FlVfsStatus_Success = 0,
    // File or path not found.
    FlVfsStatus_FileNotFound = 100,
    // Path is malformed.
    FlVfsStatus_PathInvalid = 101,
    // Path exceeds the platform limit.
    FlVfsStatus_PathTooLong = 102,
    // Expected a directory, found a file.
    FlVfsStatus_NotADirectory = 103,
    // Expected a file, found a directory.
    FlVfsStatus_IsADirectory = 104,
    // Read failed.
    FlVfsStatus_ReadError = 200,
    // Write failed.
    FlVfsStatus_WriteError = 201,
    // Seek failed.
    FlVfsStatus_SeekError = 202,
    // End of file.
    FlVfsStatus_Eof = 203,
    // Destination buffer too small.
    FlVfsStatus_BufferTooSmall = 204,
    // Access denied.
    FlVfsStatus_AccessDenied = 300,
    // Permission denied.
    FlVfsStatus_PermissionDenied = 301,
    // Out of memory.
    FlVfsStatus_OutOfMemory = 400,
    // Too many open files.
    FlVfsStatus_TooManyOpenFiles = 401,
    // Resource busy.
    FlVfsStatus_ResourceBusy = 402,
    // Disk full.
    FlVfsStatus_DiskFull = 403,
    // Generic archive error.
    FlVfsStatus_ArchiveError = 500,
    // Archive is corrupt.
    FlVfsStatus_ArchiveCorrupt = 501,
    // Archive format unsupported.
    FlVfsStatus_ArchiveUnsupported = 502,
    // Archive requires a password.
    FlVfsStatus_ArchivePasswordRequired = 503,
    // Generic network error.
    FlVfsStatus_NetworkError = 600,
    // Network timed out.
    FlVfsStatus_NetworkTimeout = 601,
    // Network unavailable.
    FlVfsStatus_NetworkUnavailable = 602,
    // DNS resolution failed.
    FlVfsStatus_NetworkDns = 603,
    // Connection refused.
    FlVfsStatus_NetworkConnectionRefused = 604,
    // SSL/TLS error.
    FlVfsStatus_NetworkSsl = 605,
    // HTTP 400 - bad request (base of the 700-799 HTTP range).
    FlVfsStatus_NetworkBadRequest = 700,
    // HTTP 401 - unauthorized.
    FlVfsStatus_NetworkUnauthorized = 701,
    // HTTP 403 - forbidden.
    FlVfsStatus_NetworkForbidden = 703,
    // HTTP 404 - not found.
    FlVfsStatus_NetworkNotFound = 704,
    // HTTP 5xx - server error.
    FlVfsStatus_NetworkServerError = 750,
    // Generic error.
    FlVfsStatus_GenericError = 900,
    // Operation not implemented by this driver.
    FlVfsStatus_NotImplemented = 901,
    // Invalid handle passed to the driver.
    FlVfsStatus_InvalidHandle = 902,
    // Operation was canceled.
    FlVfsStatus_OperationCanceled = 903,
} FlVfsStatus;

// Driver capability flags - the feature bitmask get_capabilities() returns. VFS
// core uses these to decide which operations are available. Power-of-two flags,
// OR-combined.
typedef enum FlVfsDriverCapabilities {
    // Can read files.
    FlVfsDriverCapabilities_Read = 1,
    // Can write files (future).
    FlVfsDriverCapabilities_Write = 2,
    // Can list directories.
    FlVfsDriverCapabilities_List = 4,
    // Can clone handles (multi-threading).
    FlVfsDriverCapabilities_Clone = 8,
    // Can open from memory (nested archives).
    FlVfsDriverCapabilities_Memory = 16,
    // Can provide OS file paths (optimization).
    FlVfsDriverCapabilities_DirectPath = 32,
    // Has caching support.
    FlVfsDriverCapabilities_Cache = 64,
    // Supports file watching (future).
    FlVfsDriverCapabilities_Watch = 128,
    // Is an archive format.
    FlVfsDriverCapabilities_Archive = 256,
    // Is a network filesystem.
    FlVfsDriverCapabilities_Network = 512,
} FlVfsDriverCapabilities;

// File open flags - the mode bitmask open() takes. Power-of-two flags,
// OR-combined.
typedef enum FlVfsOpenFlags {
    // Open for reading.
    FlVfsOpenFlags_Read = 1,
    // Open for writing.
    FlVfsOpenFlags_Write = 2,
    // Create if it does not exist.
    FlVfsOpenFlags_Create = 4,
    // Truncate an existing file to zero length.
    FlVfsOpenFlags_Truncate = 8,
    // Append mode (all writes go to EOF).
    FlVfsOpenFlags_Append = 16,
} FlVfsOpenFlags;

typedef struct RpPluginInfo RpPluginInfo;

typedef struct FlArena FlArena;

// Driver error detail. Always check vfs_status first; native_error carries
// the underlying errno / HTTP status / driver code for additional context.
typedef struct FlVfsDriverError {
    // VFS-level error code (always set).
    FlVfsStatus vfs_status;
    // Native error code (errno, HTTP status, etc.) or 0.
    int32_t native_error;
    // Driver-specific additional data (optional).
    uint64_t additional_data;
} FlVfsDriverError;

// Plugin creation result. Check error.vfs_status == FlVfsStatus_Success before
// using instance. Shared across plugin types (VFS, UI, etc.).
typedef struct FlPluginCreateResult {
    // Plugin instance handle, or nullptr on error.
    void* instance;
    // Error details.
    FlVfsDriverError error;
} FlPluginCreateResult;

// Open result - a driver handle or nullptr on error.
typedef struct FlVfsOpenResult {
    // Driver-specific handle, or nullptr on error.
    void* handle;
    // true if the handle is a directory/archive (can be listed).
    bool is_directory;
    // Error details.
    FlVfsDriverError error;
} FlVfsOpenResult;

// Read result - bytes read, or -1 on error.
typedef struct FlVfsReadResult {
    // Number of bytes read, or -1 on error.
    int64_t bytes_read;
    // Error details.
    FlVfsDriverError error;
} FlVfsReadResult;

// Size result - file size in bytes, or -1 on error.
typedef struct FlVfsSizeResult {
    // File size in bytes, or -1 on error.
    int64_t size;
    // Error details.
    FlVfsDriverError error;
} FlVfsSizeResult;

// Write result - bytes written, or -1 on error.
typedef struct FlVfsWriteResult {
    // Number of bytes written, or -1 on error.
    int64_t bytes_written;
    // Error details.
    FlVfsDriverError error;
} FlVfsWriteResult;

// A single file/directory entry - used in directory listings and metadata
// queries.
typedef struct FlVfsEntry {
    // Entry name (not a full path).
    FlString name;
    // File size in bytes (0 for directories).
    int64_t size;
    // Platform-specific attributes.
    uint32_t attributes;
    // true if the entry is a directory.
    bool is_directory;
    // true if the entry can be opened as an archive (e.g. a .zip file).
    bool is_archive;
} FlVfsEntry;

// Mount-level options controlling behavior for all files accessed through a
// mount. Passed by value into a driver's open; VFS core supplies it, not user
// code. The real C type is single-sourced here - `<flowi/vfs/vfs_types.h>` only
// forward-declares it (like FlVfsEntry).
typedef struct FlVfsMountOptions {
    // If set, caching plugins write here instead of the default cache. The
    // filename is derived from the URL; the directory must exist.
    FlString cache_dir;
    // If true, validate cached files against the server (ETag) before use - for
    // mutable remote files. Default (false) uses the cache without validation.
    bool cache_validation;
    // If true, start a file watcher for LocalFS mounts. Must be set before the
    // mount completes (at mount-creation time).
    bool enable_file_watching;
} FlVfsMountOptions;

// VFS Driver Plugin interface - the set of operations a driver implements to
// provide filesystem access for local files, archives, network filesystems, and
// virtual filesystems.
typedef struct FlVfsPlugin {
    // Should be set to FL_VFS_PLUGIN_API_VERSION.
    uint64_t api_version;
    // Name of the plugin.
    FlString plugin_name;
    // Plugin metadata (version, author, ...). Optional; nullptr if none.
    RpPluginInfo* plugin_info;
    // Create a driver instance.
    FlPluginCreateResult (*create)(void);
    // Destroy a driver instance from create().
    void (*destroy)(void* driver_instance);
    // Fast path-type check (no I/O) - used for driver selection.
    bool (*supports_path)(FlString path);
    // Check whether this driver can actually open the path (may do I/O).
    bool (*can_open)(FlString path);
    // Open a file or directory (relative to parent_handle, or absolute when it is
    // nullptr). mount_options is supplied by VFS core, not user code.
    FlVfsOpenResult (*open)(void* driver_instance, void* parent_handle, FlString path, uint32_t flags, FlVfsMountOptions mount_options);
    // Whether an opened handle is a directory/archive.
    bool (*is_directory)(void* driver_instance, void* handle);
    // Read file contents into the caller-owned buffer. A non-empty relative_path
    // names a file below handle and is read from its start; an empty one reads
    // the file handle was opened on, continuing from its current offset.
    FlVfsReadResult (*read)(void* driver_instance, void* handle, FlString relative_path, uint8_t* buffer, int64_t size);
    // Get a file's size. relative_path resolves against handle as it does for
    // read(). Returns -1 for a directory or a path that does not exist.
    FlVfsSizeResult (*get_size)(void* driver_instance, void* handle, FlString relative_path);
    // List directory contents, invoking callback once per entry discovered;
    // listing stops when the callback returns false.
    void (*list_directory)(void* driver_instance, void* handle, FlString relative_path, FlVfsListingCallback callback, void* user_data);
    // Clone a handle for concurrent access (each clone is independently closeable).
    FlVfsOpenResult (*clone)(void* driver_instance, void* handle);
    // Close a handle and free its resources.
    void (*close)(void* driver_instance, void* handle);
    // Driver capability flags.
    FlVfsDriverCapabilities (*get_capabilities)(void);
    // Open an archive from a memory buffer (FlVfsDriverCapabilities_Memory). On
    // success the driver takes ownership of data; on failure the caller retains
    // it. nullptr if unsupported.
    FlVfsOpenResult (*open_memory)(void* driver_instance, const uint8_t* data, uint64_t size, FlString original_path);
    // Get an OS filesystem path for a resource (FlVfsDriverCapabilities_DirectPath),
    // allocated from arena. Empty string if unavailable. nullptr if unsupported.
    FlString (*get_file_path)(void* driver_instance, void* handle, FlString relative_path, FlArena* arena);
    // Whether a path is cached and fresh (FlVfsDriverCapabilities_Cache). nullptr
    // if unsupported.
    bool (*is_cached)(void* driver_instance, FlString path);
    // Enable file watching on a handle (FlVfsDriverCapabilities_Watch). nullptr if
    // unsupported (most drivers).
    bool (*enable_watching)(void* driver_instance, void* handle);
    // Write data from the caller-owned buffer (FlVfsDriverCapabilities_Write).
    // nullptr if unsupported.
    FlVfsWriteResult (*write)(void* driver_instance, void* handle, const uint8_t* buffer, int64_t size);
} FlVfsPlugin;


#ifdef __cplusplus
}
#endif
